/* =====================================================
   OVERLAY DESIGN TEMPLATES — data.js
   
   This file contains all static template data and
   performance scores read from the Google Sheet:
   "Overlay Design Templates"
   (ID: 1ujBwVxVxpcubJq06s0mRey2QYJvfrxvIrYt1iZFaUME)

   UPDATING SCORES:
   - Scores are read from "Campaign Performance by type
     for last 3 months" tab, updated weekly.
   - To pull live scores automatically, deploy the
     "overlay stats" Apps Script as a Web App and paste
     the URL into APPS_SCRIPT_URL below.

   IMAGES:
   - One thumbnail JPG per template lives in
     automation/images/thumbs/REF.jpg — originally
     extracted from the "Screenshot" column of the
     source Google Sheet.
   - To refresh/add an image: save the thumbnail to
     images/thumbs/REF.jpg  and set
     img: 'images/thumbs/REF.jpg'  in the template entry.
   ===================================================== */

/* ── Admin password ─────────────────────────────── */
const ADMIN_PASSWORD = "overlays2025";

/* ── Apps Script URL ────────────────────────────────
   Set this to your deployed Web App URL to enable
   live score fetching on every page load.
   Leave as null to use the static SCORES below.

   Deploy steps:
     1. Open Extensions > Apps Script in the sheet
     2. Deploy > New deployment > Web App
     3. Execute as: Me | Access: Anyone
     4. Copy the URL and paste it here.
   ─────────────────────────────────────────────── */
const APPS_SCRIPT_URL =
  "https://script.google.com/macros/s/AKfycbxelkLJYarWD_CE5btpJB4ULdQUhUb9HYfRD9RvRRiU7VgRVNolKb7DbOfnie9ko5fU-Q/exec";

/* ── Performance scores ─────────────────────────────
   Source: "Campaign Performance by type for last 3
   months" tab — Engagement Rate (col E) and
   Conversion Rate (col H, = Sales / Engaged).
   Values are percentages (e.g. 10.31 = 10.31%).
   null = no data available for that metric.
   ─────────────────────────────────────────────── */
const SCORES = {
  // Dynamic Basket
  DB0001: { eng: 10.31, conv: 15.89 },
  DB0002: { eng: 22.33, conv: 35.82 },
  DB0003: { eng: 12.5, conv: 27.78 },
  DB0004: { eng: 3.41, conv: 35.33 },
  DB0005: { eng: 4.48, conv: 20.49 },
  DB0006: { eng: 0.0, conv: null },
  DB0007: { eng: 6.81, conv: 21.57 },
  DB0008: { eng: 29.04, conv: 35.57 },
  DB0009: { eng: 1.54, conv: 21.43 },
  DB0010: { eng: 16.07, conv: 5.26 },
  DB0011: { eng: null, conv: null }, // template reassigned in sheet (old "Birkenstock" score no longer applies) — reset until re-measured
  DB0012: { eng: 10.91, conv: 14.15 },
  DB0013: { eng: null, conv: null },
  DB0014: { eng: 8.64, conv: 23.94 },
  DB0015: { eng: 7.26, conv: 13.9 },
  DB0016: { eng: 3.42, conv: 8.05 },
  DB0017: { eng: 8.28, conv: 32.14 },

  // Recomminder
  PR0001: { eng: 11.19, conv: 1.82 },
  PR0002: { eng: 0.0, conv: null },
  PR0003: { eng: 9.98, conv: 14.29 },
  PR0004: { eng: 13.26, conv: 6.11 },

  // Redirect
  RD0001: { eng: 4.01, conv: 42.25 },
  RD0002: { eng: 14.62, conv: 1.3 },
  RD0003: { eng: 13.79, conv: 4.03 },
  RD0004: { eng: null, conv: null },

  // Click to Reveal
  RV0001: { eng: null, conv: null },
  RV0002: { eng: 3.89, conv: 10.17 },
  RV0003: { eng: null, conv: null },
  RV0004: { eng: 9.91, conv: 2.92 },

  // Miscellaneous
  MS0001: { eng: null, conv: null },
  MS0002: { eng: null, conv: null },
  MS0003: { eng: 2.09, conv: 6.29 },
  MS0004: { eng: 50.0, conv: 0.0 },
  MS0011: { eng: null, conv: null },
  MS0012: { eng: null, conv: null },
  MS0013: { eng: null, conv: null },
};

/* ── Templates ──────────────────────────────────────
   Fields:
     ref   — unique reference code (e.g. "DB0001")
     cat   — category key: db | pr | rd | rv | ms
     desc  — description from the sheet
     url   — Intent.ly preview URL (full URL)
     img   — image path or URL (null = show placeholder)
               Local: 'images/thumbs/DB0001.jpg'
               Remote: full URL
     notes — optional notes from the sheet
     upvotes    — number of upvotes (default 0)
     downvotes  — number of downvotes (default 0)
   ─────────────────────────────────────────────── */
const TEMPLATES = [
  /* ── Dynamic Basket ─────────────────────────── */
  {
    ref: "DB0001",
    cat: "db",
    desc: "Simple Dynamic basket overlay",
    url: "https://admin.intent.ly/my-account/overlay-manager/#129190",
    img: "images/thumbs/DB0001.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0002",
    cat: "db",
    desc: "Dynamic basket overlay with animated icon for attention",
    url: "https://admin.intent.ly/my-account/overlay-manager/#139425",
    img: "images/thumbs/DB0002.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0003",
    cat: "db",
    desc: "Small format dynamic basket overlay, minimal design for when very little copy is required or supplied",
    url: "https://admin.intent.ly/my-account/overlay-manager/#142876",
    img: "images/thumbs/DB0003.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0004",
    cat: "db",
    desc: "Dynamic basket with a 50/50 layout of messaging and basket section",
    url: "https://admin.intent.ly/my-account/overlay-manager/#149571",
    img: "images/thumbs/DB0004.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0005",
    cat: "db",
    desc: "Bottom left unobtrusive design",
    url: "https://admin.intent.ly/my-account/overlay-manager/#149581",
    img: "images/thumbs/DB0005.jpg",
    notes:
      "Can be positioned bottom left, bottom right, top left, top right — specify when adding ticket in HubSpot",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0006",
    cat: "db",
    desc: "Corner overlay with just the product details and a hover effect",
    url: "https://admin.intent.ly/my-account/overlay-manager/#121004",
    img: "images/thumbs/DB0006.jpg",
    notes:
      "Can be positioned bottom left, bottom right, top left, top right — specify when adding ticket in HubSpot",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0007",
    cat: "db",
    desc: "Dynamic basket with space for USPs that rotate",
    url: "https://admin.intent.ly/my-account/overlay-manager/#151335",
    img: "images/thumbs/DB0007.jpg",
    notes:
      "The default design for this balances the text with the right aligned product section by having left aligned text, please specify if you want to change this to centred text",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0008",
    cat: "db",
    desc: "Dynamic basket with layout that is specific to date based reservations like hotels or events",
    url: "https://admin.intent.ly/my-account/overlay-manager/#154632",
    img: "images/thumbs/DB0008.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0009",
    cat: "db",
    desc: "Dynamic basket sidebar with USP list under product information",
    url: "https://admin.intent.ly/my-account/overlay-manager/#159534",
    img: "images/thumbs/DB0009.jpg",
    notes:
      "Can be positioned bottom left, bottom right, top left, top right — specify when adding ticket in HubSpot",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0010",
    cat: "db",
    desc: "Letterbox style long thin dynamic basket",
    url: "https://admin.intent.ly/my-account/overlay-manager/#159810",
    img: "images/thumbs/DB0010.jpg",
    notes:
      "Can be positioned bottom left, bottom right, top left, top right — specify when adding ticket in HubSpot",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0011",
    cat: "db",
    desc: "Bento box styled overlay that organises the elements automatically",
    url: "https://admin.intent.ly/my-account/overlay-manager/#195237",
    img: "images/thumbs/DB0011.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0012",
    cat: "db",
    desc: "Fashion simple",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161367",
    img: "images/thumbs/DB0012.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0013",
    cat: "db",
    desc: "Basket reminder with central product section",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161587",
    img: "images/thumbs/DB0013.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0014",
    cat: "db",
    desc: "Bottom left compact design with hover effect to highlight product",
    url: "https://admin.intent.ly/my-account/overlay-manager/#162194",
    img: "images/thumbs/DB0014.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0015",
    cat: "db",
    desc: "Standard template for products with company branding",
    url: "https://admin.intent.ly/my-account/overlay-manager/#165015",
    img: "images/thumbs/DB0015.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0016",
    cat: "db",
    desc: "VERY non intrusive example with just product details and price integrated into the button",
    url: "https://admin.intent.ly/my-account/overlay-manager/#166247",
    img: "images/thumbs/DB0016.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0017",
    cat: "db",
    desc: "Simple basket reminder overlay bottom left",
    url: "https://admin.intent.ly/my-account/overlay-manager/#167151",
    img: "images/thumbs/DB0017.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0018",
    cat: "db",
    desc: "Left right layout using flex CSS functionality",
    url: "https://admin.intent.ly/my-account/overlay-manager/#198868",
    img: "images/thumbs/DB0018.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0019",
    cat: "db",
    desc: "Dynamic basket and voucher reveal using flex layout",
    url: "https://admin.intent.ly/my-account/overlay-manager/#172354",
    img: "images/thumbs/DB0019.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "DB0020",
    cat: "db",
    desc: "Dynamic basket focussing on product image with minimal details",
    url: "https://admin.intent.ly/my-account/overlay-manager/#197996",
    img: "images/thumbs/DB0020.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },

  /* ── Recomminder ─────────────────────────────── */
  {
    ref: "PR0001",
    cat: "pr",
    desc: "Simple product recommender overlay with USPs scrolling along the bottom",
    url: "https://admin.intent.ly/my-account/overlay-manager/#149609",
    img: "images/thumbs/PR0001.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0002",
    cat: "pr",
    desc: "Female focussed recommender with woman looking at phone",
    url: "https://admin.intent.ly/my-account/overlay-manager/#149898",
    img: "images/thumbs/PR0002.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0003",
    cat: "pr",
    desc: "Side by side product recommender with two products",
    url: "https://admin.intent.ly/my-account/overlay-manager/#149896",
    img: "images/thumbs/PR0003.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0004",
    cat: "pr",
    desc: "Standard Square design",
    url: "https://admin.intent.ly/my-account/overlay-manager/#159036",
    img: "images/thumbs/PR0004.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0005",
    cat: "pr",
    desc: "Side by side product recommender with two products and a brand image",
    url: "https://admin.intent.ly/my-account/overlay-manager/#160463",
    img: "images/thumbs/PR0005.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0006",
    cat: "pr",
    desc: "Product recommender bottom left",
    url: "https://admin.intent.ly/my-account/overlay-manager/#177670",
    img: "images/thumbs/PR0006.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0007",
    cat: "pr",
    desc: '"Birkenstock" style recommender',
    url: "https://admin.intent.ly/my-account/overlay-manager/#161471",
    img: "images/thumbs/PR0007.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0008",
    cat: "pr",
    desc: "Standard two product recommender",
    url: "https://admin.intent.ly/my-account/overlay-manager/#165016",
    img: "images/thumbs/PR0008.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0009",
    cat: "pr",
    desc: "Very non intrusive example with minimal messaging",
    url: "https://admin.intent.ly/my-account/overlay-manager/#166248",
    img: "images/thumbs/PR0009.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0010",
    cat: "pr",
    desc: "Product recommender that opens once a badge/button has been clicked",
    url: "https://admin.intent.ly/my-account/overlay-manager/#160845",
    img: "images/thumbs/PR0010.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "PR0011",
    cat: "pr",
    desc: "Very simple recommender example that performed very well for fashionette",
    url: "https://admin.intent.ly/my-account/overlay-manager/#187590",
    img: "images/thumbs/PR0011.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },

  /* ── Redirect ────────────────────────────────── */
  {
    ref: "RD0001",
    cat: "rd",
    desc: "Simple basket recommender overlay for health/beauty clients",
    url: "https://admin.intent.ly/my-account/overlay-manager/#160834",
    img: "images/thumbs/RD0001.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0002",
    cat: "rd",
    desc: "Multi CTA for different categories or bestsellers",
    url: "https://admin.intent.ly/my-account/overlay-manager/#160836",
    img: "images/thumbs/RD0002.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0003",
    cat: "rd",
    desc: "Multi CTA with different images for each category/product option on hover",
    url: "https://admin.intent.ly/my-account/overlay-manager/#139633",
    img: "images/thumbs/RD0003.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0004",
    cat: "rd",
    desc: "Product category carousel sliding images",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161013",
    img: "images/thumbs/RD0004.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0005",
    cat: "rd",
    desc: "Simple multi CTA overlay with animated buttons for attention",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161314",
    img: "images/thumbs/RD0005.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0006",
    cat: "rd",
    desc: "Carousel for category page redirect, auto animates",
    url: "https://admin.intent.ly/my-account/overlay-manager/#123560",
    img: "images/thumbs/RD0006.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0007",
    cat: "rd",
    desc: "Roundel redirect that sits on the periphery of the site design and animates in like a sticker",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161445",
    img: "images/thumbs/RD0007.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0008",
    cat: "rd",
    desc: "Simple Click to redirect with brand image to the left",
    url: "https://admin.intent.ly/my-account/overlay-manager/#163199",
    img: "images/thumbs/RD0008.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0009",
    cat: "rd",
    desc: "Simple Click to redirect with brand image at the top",
    url: "https://admin.intent.ly/my-account/overlay-manager/#163200",
    img: "images/thumbs/RD0009.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0010",
    cat: "rd",
    desc: "Generic Static basket redirect",
    url: "https://admin.intent.ly/my-account/overlay-manager/#157441",
    img: "images/thumbs/RD0010.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0011",
    cat: "rd",
    desc: "Simple redirect with timer bar to add urgency",
    url: "https://admin.intent.ly/my-account/overlay-manager/#163568",
    img: "images/thumbs/RD0011.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0012",
    cat: "rd",
    desc: "Simple multi CTA overlay with product images and buttons with hover effects",
    url: "https://admin.intent.ly/my-account/overlay-manager/#163927",
    img: "images/thumbs/RD0012.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0013",
    cat: "rd",
    desc: "Multi CTA overlay with category images and a text hover effect",
    url: "https://admin.intent.ly/my-account/overlay-manager/#166088",
    img: "images/thumbs/RD0013.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0014",
    cat: "rd",
    desc: "Video background overlay",
    url: "https://admin.intent.ly/my-account/overlay-manager/#167051",
    img: "images/thumbs/RD0014.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0015",
    cat: "rd",
    desc: "Redirect overlay with dynamic shaped image and button outside of the standard position",
    url: "https://admin.intent.ly/my-account/overlay-manager/#167531",
    img: "images/thumbs/RD0015.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0016",
    cat: "rd",
    desc: "Copy to reveal overlay, this overlay appears when the user copies the title on a product page",
    url: "https://admin.intent.ly/my-account/overlay-manager/#171989",
    img: "images/thumbs/RD0016.jpg",
    notes:
      "Figma file for badge can be found here: https://www.figma.com/design/BBqNa5KdU9SzuFg1NyiyhB/price-promise-badge?node-id=0-1&t=CPpQlxuvTRrEtTjY-1",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0016b",
    cat: "rd",
    desc: "Traffic shaping or offer highlighting overlay with branded colours",
    url: "https://admin.intent.ly/my-account/overlay-manager/#178036",
    img: "images/thumbs/RD0016b.jpg",
    notes:
      "⚠ The source sheet lists this as a SECOND row numbered RD0016 — please assign it a unique reference code in the sheet.",
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0017",
    cat: "rd",
    desc: "Frequently bought together",
    url: "https://admin.intent.ly/my-account/overlay-manager/#181108",
    img: "images/thumbs/RD0017.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0018",
    cat: "rd",
    desc: "Nudge Bottom Left Horizontal",
    url: "https://admin.intent.ly/my-account/overlay-manager/#184699",
    img: "images/thumbs/RD0018.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0019",
    cat: "rd",
    desc: "Multi CTA Simple Small business",
    url: "https://admin.intent.ly/my-account/overlay-manager/#188000",
    img: "images/thumbs/RD0019.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0020",
    cat: "rd",
    desc: "Classic split with Scrolling USPs",
    url: "https://admin.intent.ly/my-account/overlay-manager/#193264",
    img: "images/thumbs/RD0020.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RD0021",
    cat: "rd",
    desc: "Multiple CTAs",
    url: "https://admin.intent.ly/my-account/overlay-manager/#199030",
    img: "images/thumbs/RD0021.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },

  /* ── Click to Reveal ─────────────────────────── */
  {
    ref: "RV0001",
    cat: "rv",
    desc: "Simple code reveal template with space for images positioned absolutely to the right",
    url: "https://admin.intent.ly/my-account/overlay-manager/#153895",
    img: "images/thumbs/RV0001.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0002",
    cat: "rv",
    desc: "Simple code reveal with imagery to the left",
    url: "https://admin.intent.ly/my-account/overlay-manager/#166077",
    img: "images/thumbs/RV0002.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0003",
    cat: "rv",
    desc: "Click to reveal template",
    url: "https://admin.intent.ly/my-account/overlay-manager/#198989",
    img: "images/thumbs/RV0003.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0004",
    cat: "rv",
    desc: "Click to reveal overlay with new customer banner and brand image in a compact form",
    url: "https://admin.intent.ly/my-account/overlay-manager/#171740",
    img: "images/thumbs/RV0004.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0005",
    cat: "rv",
    desc: "Copy to reveal, the overlay gets positioned relative to an element on the client's page",
    url: "https://admin.intent.ly/my-account/overlay-manager/#183766",
    img: "images/thumbs/RV0005.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0006",
    cat: "rv",
    desc: "Minimal click to reveal",
    url: "https://admin.intent.ly/my-account/overlay-manager/#192602",
    img: "images/thumbs/RV0006.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0007",
    cat: "rv",
    desc: "THG Accessibility compliant click to reveal",
    url: "https://admin.intent.ly/my-account/overlay-manager/#192771",
    img: "images/thumbs/RV0007.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "RV0008",
    cat: "rv",
    desc: "Classic image text split with blurred out code section that focusses when revealed",
    url: "https://admin.intent.ly/my-account/overlay-manager/#193249",
    img: "images/thumbs/RV0008.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },

  /* ── Miscellaneous ───────────────────────────── */
  {
    ref: "MS0001",
    cat: "ms",
    desc: "Small badge opens click to reveal (preview overlay to see full functionality)",
    url: "https://admin.intent.ly/my-account/overlay-manager/#160538",
    img: "images/thumbs/MS0001.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0002",
    cat: "ms",
    desc: "Bottom left click to expand email voucher overlay (preview overlay to see full functionality)",
    url: "https://admin.intent.ly/my-account/overlay-manager/#161370",
    img: "images/thumbs/MS0002.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0003",
    cat: "ms",
    desc: "Email to reveal basic layout, can be adapted to most brands quite easily",
    url: "https://admin.intent.ly/my-account/overlay-manager/#173498",
    img: "images/thumbs/MS0003.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0004",
    cat: "ms",
    desc: "Email voucher overlay with voucher icon and terms link that needs to be updated",
    url: "https://admin.intent.ly/my-account/overlay-manager/#173512",
    img: "images/thumbs/MS0004.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0005",
    cat: "ms",
    desc: "Spin the wheel template, can be either click to reveal or email to reveal",
    url: "https://admin.intent.ly/my-account/overlay-manager/#180672",
    img: "images/thumbs/MS0005.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0006",
    cat: "ms",
    desc: "Accessibility compliant click to reveal overlay for THG brands. Timer with start and end times (THG)",
    url: "https://admin.intent.ly/my-account/overlay-manager/#186004",
    img: "images/thumbs/MS0006.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0007",
    cat: "ms",
    desc: "Email collection for basket Backup",
    url: "https://admin.intent.ly/my-account/overlay-manager/#184767",
    img: "images/thumbs/MS0007.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0008",
    cat: "ms",
    desc: "Accessibility compliant click to redirect overlay for THG brands",
    url: "https://admin.intent.ly/my-account/overlay-manager/#187784",
    img: "images/thumbs/MS0008.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0009",
    cat: "ms",
    desc: "Email to reveal landscape layout",
    url: "https://admin.intent.ly/my-account/overlay-manager/#187974",
    img: "images/thumbs/MS0009.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0010",
    cat: "ms",
    desc: "Giftcloud template",
    url: "https://admin.intent.ly/my-account/overlay-manager/#190539",
    img: "images/thumbs/MS0010.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0011",
    cat: "ms",
    desc: "Basic email to reveal",
    url: "https://admin.intent.ly/my-account/overlay-manager/#198669",
    img: "images/thumbs/MS0011.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0012",
    cat: "ms",
    desc: "Trustpilot",
    url: "https://admin.intent.ly/my-account/overlay-manager/#198738",
    img: "images/thumbs/MS0012.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
  {
    ref: "MS0013",
    cat: "ms",
    desc: "Gamified multi-step quiz with branching answers, ending in a reveal, email capture or redirect",
    url: "https://admin.intent.ly/my-account/overlay-manager/#199088",
    img: "images/thumbs/MS0013.jpg",
    notes: null,
    upvotes: 0,
    downvotes: 0,
  },
];
